### ISSUE TITLE
Moving left on a slope teleports the player

### ISSUE THREAD

**Issue by svercl** [RandyGaul/player2d#7]
![As you can see here](https://user-images.githubusercontent.com/3598852/54035439-fa262780-417e-11e9-9b51-26555d37295f.gif)

**Comment by RandyGaul** [comment]
It’s a bug with collision normal flipping in some cases. I just need to do an audit and make sure normal sign is always consistent.

**Comment by RandyGaul** [comment]
I got a 100% repro using the frame-stepping code. Turns out to be an order of operations bug in the player stepping logic in main.cpp. There was a case where the sweep would return 1.0f, signaling freedom to move forward, and would exit the loop before applying any NGS. When running up a slope, this means the `skin_buffer` can be violated just as the player goes over an edge, since NGS was skipped.

There were also some minor bugs with c2CapsuletoPolyManifold, but had no real effect on the way the character performed.

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/player2d/commit/4c72fc1b9c5ddf3b73263897e71974c5173271d1

**Comment by RandyGaul** [comment]
Specifically here:

![image](https://user-images.githubusercontent.com/1919825/54055667-9b72a500-41a2-11e9-8b11-76342bb9a148.png)
